FROM alpine:edge
MAINTAINER Mark Riedesel <mark@klowner.com>

RUN echo "http://dl-4.alpinelinux.org/alpine/v3.3/testing" >> /etc/apk/repositories \
	echo "http://

RUN apk update \
	&& apk add \
		openssh-client \
		clang \
		cmake \
		make \
		g++ \
		gcc \
		git

